apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: pantry
    labels:
        app.kubernetes.io/part-of: pantry
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:rQl1X5QW,iv:Zlkziz9X8C+HPwYFGYL5+ngTqIoO4j3uJWY3Ox1Iam0=,tag:3Pmvb6nrCn0lz3BLDtYoWw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:urzgrSi3WI3H1NwZZZOnwdbK/Ln0BO/bELWDGhL31XNJ,iv:RAqxc6fEDU1YkQl4hLkTLsHsXGO1JeYlc17rc+dbo6Y=,tag:AGi+cP2cEHeF5ut07KQ88g==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:T3poyneg,iv:Oebr9LSnj2ZSFzRbQhr5TvrCdOFNA7/Bc8RiK5Ag66E=,tag:2jlhsBuKF34kGMWfsp82zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcktBMFJ4OGRHVmZEOTRv
            dFd5NmUrY3oyY0hJWGxLY0QvSGRBVC9HSTBZCjNCR3ltSERadW85T0doWWtuY2Rk
            dDJEZFlodFVVaWZjakxUeCs2R0V5S2cKLS0tIGtXQ2RaemVuUkNHNkR3eGdQT1Bu
            S2t6dlhDR244WHY4ZmFSaXYvUW9zRlUKtPzI1xVZU6ntfYGksoUSrhqdykO6KEjj
            KQQtkdifG2uUmYcfLhO4y60pqDY6HvKmHiBPLwQhgq/hp09SIV+IwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1njz0lg0xzkpn5lhvx04hszk0zwdp9v23zq8pjlad3cvwpz284e3sjxlgq3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T16:16:51Z"
    mac: ENC[AES256_GCM,data:lpMj4sD335RcXYKRCC3baoELR56NVml1kLVmgTGKsaAk9ZKXI5PgtQlqM+1eMWrT8KmE7QC8OABh1ax5eqiXKkBQbWYrRQ7YeMVpbAG3Ze5Hh4UCtRNl2c/P6LtZuXjyOxY8UQN8TI3uj0B+k1KEWm1uexXSUt15cAgkoTnZk68=,iv:gxqXmPhQLDoels2Ju7V70Ip4hY34YL469p37eIeAjMM=,tag:CW+gHCMaxyzlyj76fuY1Kg==,type:str]
    version: 3.13.3
