apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: pantry
    labels:
        app.kubernetes.io/part-of: pantry
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:rQl1X5QW,iv:Zlkziz9X8C+HPwYFGYL5+ngTqIoO4j3uJWY3Ox1Iam0=,tag:3Pmvb6nrCn0lz3BLDtYoWw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vrkNCJhjBcY/y4BmSozkb8saSBj64a+EQVRVuZP0Rh0=,iv:uvXZrvE4UvkXYw7BEoj0OJqXHDWAA8WS1Rj/iBMzvC0=,tag:iWqyC8JjHHJTZQ3Of8GseA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:T3poyneg,iv:Oebr9LSnj2ZSFzRbQhr5TvrCdOFNA7/Bc8RiK5Ag66E=,tag:2jlhsBuKF34kGMWfsp82zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcktBMFJ4OGRHVmZEOTRv
            dFd5NmUrY3oyY0hJWGxLY0QvSGRBVC9HSTBZCjNCR3ltSERadW85T0doWWtuY2Rk
            dDJEZFlodFVVaWZjakxUeCs2R0V5S2cKLS0tIGtXQ2RaemVuUkNHNkR3eGdQT1Bu
            S2t6dlhDR244WHY4ZmFSaXYvUW9zRlUKtPzI1xVZU6ntfYGksoUSrhqdykO6KEjj
            KQQtkdifG2uUmYcfLhO4y60pqDY6HvKmHiBPLwQhgq/hp09SIV+IwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1njz0lg0xzkpn5lhvx04hszk0zwdp9v23zq8pjlad3cvwpz284e3sjxlgq3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T13:59:39Z"
    mac: ENC[AES256_GCM,data:s3Kh+H7XNCcfElb9/4HIweB2PrIhClAuDbV4KB7yf1E3MpsuwOza27lK6vGLsuF7L/26sbV1aLhFGndtvSzLp1V5fPOAE1DvcOM67hAxz/e0BiFFRDagIdtJH4qRMbHT/Fzrls1xOfNo2mU6DbgHqtEhl1/xRYey1MqIogXu9aE=,iv:L8AeO2kVPqyhxTmZuCCmFChJiIfirXsiOMBd4JRaJ6A=,tag:Zn7kLPSSqtMyMQB1RZ56sg==,type:str]
    version: 3.13.3
