apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pharmlovex/homelab-gitops.git
    targetRevision: main
    path: apps/stirling-pdf
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
